### ISSUE TITLE
Templates: Streaming Theatre Template Publishing Window displays incorrect information

### ISSUE THREAD

**Issue by EzioDCL** [decentraland/creator-hub#131]
**Describe the bug**
When using the Streaming Theatre Template and trying to Publish the scene, some incorrect information is auto-filled under the NAME section.
mgoldman.dcl.eth appears as one of the available NAMEs instead of the correct NAME information.
It seems that this incorrect information comes from the scene.json file under the worldConfiguration parameter line.
Tested in v0.6.0

**To Reproduce**

1. Create a new scene
2. Choose the Streaming Theatre Template
3. Once in the Inspector, press "Publish"
4. Notice that "mgoldman.dcl.eth" appears under the NAME selector

**Expected behavior**
NAME selection component should show only what's available for the current user

**Screenshots**
<img width="626" alt="Decentraland_Creator_Hub_m2w6ulOz6y" src="https://github.com/user-attachments/assets/47dce1b6-75e6-4b86-9047-d2be6be6680f">
<img width="209" alt="Code_gagd6LSyiO" src="https://github.com/user-attachments/assets/d00ffb89-a533-4e90-9edb-2b9c390a4312">

**Comment by cyaiox** [comment]
Fixed for the creator-hub here: https://github.com/decentraland/creator-hub/pull/127
