### ISSUE TITLE
Inspector: "Back" button should take users to the Scenes Tab

### ISSUE THREAD

**Issue by EzioDCL** [decentraland/creator-hub#137]
**Describe the bug**
Currently, when pressing the "Back" button inside the Scene Edit Screen, the user is taken back to the last visited screen (For example, the Templates screen, or the Home screen). Users should always go to the "Scenes" when pressing this button.

**To Reproduce**

1. Create a New Scene from any template
2. Once the scene is open, click the "Back" button at the top left corner of the screen
3. Notice that you will be taken back to the "Templates" screen instead of the "Scenes" screen
4. This also applies when entering a scene directly form the "Home" Tab

**Expected behavior**
When pressing the "Back" button, users should go to the "Scenes" Tab, not to the Templates or Home screens

<img width="884" alt="Figma_coSLflV1Nc" src="https://github.com/user-attachments/assets/394cf92e-7ce3-45d6-88bf-8b0fbf093192">

**Additional context**
Figma Flow: https://www.figma.com/design/Haf9dPjUb6aytHV8T0Oelq/%F0%9F%A7%B0-Creator-Hub-%7C-Cycle-8?node-id=9434-33011&t=dwBoXk5Y87K66gsJ-4

**Comment by cyaiox** [comment]
Fixed in: https://github.com/decentraland/creator-hub/pull/134

The fix is in the latest pre-release
