### ISSUE TITLE
Templates: scenes and templates disappear from the Hub

### ISSUE THREAD

**Issue by EzioDCL** [decentraland/creator-hub#141]
**Describe the bug**
If the user attempts to open a recently deleted scene while it's still listed in My Scenes, an empty "Test Scene" scene will be open instead. The next time the user launches the Creator Hub, all scenes (Deleted and undeleted ones) will disappear from the "My Scenes" list. Also, when trying to create a new Scene, Templates will be also missing from the Template list.
Found on v0.6.0

**To Reproduce**

1. Open the Creator Hub and have some scenes created or imported into "My Scenes"
2. In your hard disk, go to your Scenes folder
3. Delete one or more scenes from your hard disk while the Creator Hub it's still open
4. Try to open one of the deleted scenes
5. Notice that a "Test Scene" will be open instead
6. Close and reopen the Creator Hub App
7. Notice that the "My Scenes" list it's now empty
8. Try to create a new Scene
9. Notice that the Templates are also missing

**Expected behavior**
- Deleting scene folders should trigger a Missing Reference message instead of just disappearing from the list
- "Test Scene" scenes should not be created in the absence of any other scene folder.
- Templates should be always available in the Template list.

**Screenshots**
https://github.com/user-attachments/assets/cf0db064-5a40-421b-9b0c-124e7c0123d8

**Comment by cazala** [comment]
mm i'm not seeing that behaviour on the pre-release version 0.7.0

What happens is that when I delete a scene from the scene folder, and I try to open it, it won't load, but it does not show a test scene, it just doesn't load.

After I refresh or reopen the editor, I do see the missing reference alert and I'm able to delete it from the list or fix it. Also the templates work fine afterwards.

https://github.com/user-attachments/assets/26df1b3f-37ea-46d1-89b7-d3180f0e81fb

**Comment by EzioDCL** [comment]
This was found on v0.6.0
Let me test it on the newer one so we can close it.
