### ISSUE TITLE
Templates: Streaming Theatre Template description is confusing

### ISSUE THREAD

**Issue by EzioDCL** [decentraland/creator-hub#150]
**Describe the bug**
The current Streaming Theatre Template description is "If there is a picture, there is a video", While the description is funny, it may confuse some users or be off-putting to others.

**To Reproduce**

1. Create a new scene using the Streaming Theatre Template
2. Open it and attempt to publish it
3. In the Publish window, select "Publish to Worlds" and advance until the Linker App opens in your browser
4. Notice the description text under the Title
5. You can also see this text opening the scene.json file

**Expected behavior**
Descriptions should help users understand the value and functionality of the templates

**Screenshots**
![Image](https://github.com/user-attachments/assets/9a00af99-dc3e-469f-ae7e-d6124d15f000)
![Image](https://github.com/user-attachments/assets/7d6adeea-5262-4ddf-aaf8-ab9ea8f4444f)

**Additional context**
Tested and found on v0.7.0

**Comment by nearnshaw** [comment]
Fixed, changed the description to
"Stream live or prerecorded videos into a large screen in this scene."
