### ISSUE TITLE
Make hover glow optional

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/creator-hub#160]
In the explorer alpha, any item that is intractable glows with a green frame. There is no way to disable this, which can sometimes be a problem.

For example if we want to have an invisible click area, it will always glow:

![Image](https://github.com/user-attachments/assets/7bae3e81-66f0-40ba-b506-4ced330d7c74)

We should add a property to the PointerEvents component (and to the helpers), to make this glow optional. It should be enabled by default, but creators who wish to hide it can remove it.

**Comment by pravusjif** [comment]
Implemented at https://github.com/decentraland/unity-explorer/pull/2651, will reach production with E@ `v0.41`.

There's now a new `showHighlight` property in the pointer events component (and helper).
